In [1]:
# Import dependencies
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import psycopg2
from ipython_config import RDS_pwd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.naive_bayes import ComplementNB,GaussianNB
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.linear_model import Lasso, LogisticRegression, LinearRegression 
from sklearn.feature_selection import SelectFromModel 
from sklearn.ensemble import RandomForestClassifier 
from imblearn.metrics import classification_report_imbalanced
from imblearn.over_sampling import SMOTE
from collections import Counter
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint
import pickle
import os
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
import matplotlib.pyplot as plt
import joblib
import h5py
import statsmodels.formula.api as sm

In [2]:
# Connect to database (Note: The package psychopg2 is required for Postgres to work with SQLAlchemy)
db_string = f"postgres://postgres:{RDS_pwd}@platinum-rds.cbu3an3ywyth.us-east-2.rds.amazonaws.com/Platinum_Lyrics"
engine = create_engine(db_string)

In [3]:
#printing names of the tables present in the database
print(engine.table_names())

['pivot', 'spotify', 'bb_id', 'bb_no_id', 'million_songs', 'pivot_songs', 'pivot_songs_bb', 'platinum_lyrics', 'platinum_features', 'platinum_lyrics_features', 'pivot_spotify', 'platinum_spotify', 'word_freq']


In [4]:
# lyrics_features = engine.table_names()[0]
lyrics_only = engine.table_names()[7]
lyrics_only

'platinum_lyrics'

In [5]:
# Read SQL database table into a DataFrame.
lyrics_only_df = pd.read_sql_table(lyrics_only,engine)
lyrics_only_df.head()

track_id                                      artist_name  \
0  TRSYKBX128F427F0F1                                  wilson phillips   
1  TRSYKCU128F4277A59                                          stryper   
2  TRSYKHG12903CEDBD6                                        sam cooke   
3  TRSYKNK128F933B674  up up down down left right left right b a start   
4  TRSYLQO128F931B4A3                                    alison krauss   

                               song_title  song_year  target_success  \
0                            get together       2004               0   
1                    always there for you       1988               1   
2                      crazy she calls me       2000               0   
3  i know you'll find out that i'm a geek       2003               0   
4                             crazy faith       2001               0   

   target_weeks  target_peak  word_abov  word_accept  word_ach  ...  \
0             0            0          0            0         0  ...   
1            71            8          0            0         0  ...   
2             0            0          0            0         0  ...   
3             0            0          0            0         0  ...   
4             0            0          1            0         0  ...   

   word_yeah  word_year  word_yellow  word_yes  word_yesterday  word_yet  \
0          0          0            0         0               0         0   
1          0          0            0         0               0         0   
2          0          0            0         0               0         0   
3          0          1            0         0               0         0   
4          0          0            0         0               0         3   

   word_york  word_young  word_yourself  word_youth  
0          0           0              0           0  
1          0           0              0           0  
2          0           0              0           0  
3          0           0              0           0  
4          0           0              0           0  

[5 rows x 1552 columns]

In [6]:
# Remove the prefix "word_":
column_names = lyrics_only_df.columns.values
new_column_names = {}
for column in column_names:
                new_column_names[column] = column.replace('word_', '')
lyrics_only_df = lyrics_only_df.rename(columns=new_column_names)

# PREPROCESSING

In [7]:
# Get the shape of lyrics_only_df 
lyrics_only_df.shape

(39094, 1552)

In [8]:
# Get list of columns
list(lyrics_only_df.columns)

['track_id',
 'artist_name',
 'song_title',
 'song_year',
 'target_success',
 'target_weeks',
 'target_peak',
 'abov',
 'accept',
 'ach',
 'across',
 'act',
 'action',
 'addict',
 'admit',
 'ador',
 'afraid',
 'against',
 'age',
 'ago',
 'ahead',
 'aim',
 'air',
 'album',
 'algo',
 'aliv',
 'alla',
 'alma',
 'almost',
 'alon',
 'along',
 'alreadi',
 'alright',
 'although',
 'alway',
 'amaz',
 'america',
 'american',
 'amigo',
 'amo',
 'amor',
 'amour',
 'angel',
 'anger',
 'ani',
 'anim',
 'anoth',
 'answer',
 'ant',
 'anybodi',
 'anymor',
 'anyon',
 'anyth',
 'anyway',
 'anywher',
 'apart',
 'appear',
 'arm',
 'around',
 'arriv',
 'art',
 'ash',
 'ask',
 'asleep',
 'ass',
 'att',
 'attack',
 'aus',
 'aux',
 'awak',
 'away',
 'babe',
 'babi',
 'back',
 'bad',
 'bag',
 'ball',
 'band',
 'bang',
 'bank',
 'bar',
 'bare',
 'bass',
 'battl',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'bed',
 'beer',
 'befor',
 'beg',
 'began',
 'begin',
 'begun',
 'beh

In [9]:
# Get columns with null values
null_columns=lyrics_only_df.columns[lyrics_only_df.isnull().any()]
lyrics_only_df[null_columns].isnull().sum()

Series([], dtype: float64)

In [10]:
# Drop columns we don't need 
lyrics_only_df.drop(columns=["track_id","artist_name",
                                              "song_title","song_year","target_weeks",
                                              "target_peak"],axis=1,inplace=True)
lyrics_only_df.head()


target_success  abov  accept  ach  across  act  action  addict  admit  \
0               0     0       0    0       0    0       0       0      0   
1               1     0       0    0       0    0       0       0      0   
2               0     0       0    0       0    0       0       0      0   
3               0     0       0    0       0    0       0       0      0   
4               0     1       0    0       0    0       0       0      0   

   ador  ...  yeah  year  yellow  yes  yesterday  yet  york  young  yourself  \
0     0  ...     0     0       0    0          0    0     0      0         0   
1     0  ...     0     0       0    0          0    0     0      0         0   
2     0  ...     0     0       0    0          0    0     0      0         0   
3     0  ...     0     1       0    0          0    0     0      0         0   
4     0  ...     0     0       0    0          0    3     0      0         0   

   youth  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 1546 columns]

In [11]:
# Remove some noisy features found through previous runs of the model
lyrics_only_df.drop(columns=["ooh","con","una","por","noth","mai","whi","como","qui",
                            "qui", "das", "doe", "der", "des", "dan",
                             "che", "mani", "vida", "mit", "pas", "per",
                             "cos", "mir", "nos", "dir", "poi", "voi",
                             "och", "ver", "mari", "har", "doo", "ima"],
                    axis=1,inplace=True)
lyrics_only_df.head()

target_success  abov  accept  ach  across  act  action  addict  admit  \
0               0     0       0    0       0    0       0       0      0   
1               1     0       0    0       0    0       0       0      0   
2               0     0       0    0       0    0       0       0      0   
3               0     0       0    0       0    0       0       0      0   
4               0     1       0    0       0    0       0       0      0   

   ador  ...  yeah  year  yellow  yes  yesterday  yet  york  young  yourself  \
0     0  ...     0     0       0    0          0    0     0      0         0   
1     0  ...     0     0       0    0          0    0     0      0         0   
2     0  ...     0     0       0    0          0    0     0      0         0   
3     0  ...     0     1       0    0          0    0     0      0         0   
4     0  ...     0     0       0    0          0    3     0      0         0   

   youth  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 1514 columns]

In [12]:
# Get data types 
for dtype in lyrics_only_df.dtypes: 
    print(dtype)

int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int64
int6

# FEATURE ENGINEERING

In [13]:
# Split data to test and train
X = lyrics_only_df.drop(columns=['target_success'],axis=1)
y = lyrics_only_df['target_success']

METHOD 1 - Sequential Backward Selection

In [14]:
#Sequential backward selection(sbs)
# sbs = SFS(LinearRegression(), 
#           k_features=100, 
#           forward=False, 
#           floating=False,
#           cv=0)
# sbs.fit(X, y)
# sbs.k_feature_names_


In [15]:
# Split train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1,stratify=y)

In [16]:
# Resample 
X_resampled, y_resampled = SMOTE(random_state=1).fit_resample(
    X_train, y_train
)
Counter(y_resampled)

Counter({0: 24225, 1: 24225})

In [17]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler= scaler.fit(X_resampled)

# Scale the data
X_train_scaled = X_scaler.transform(X_resampled)
X_test_scaled = X_scaler.transform(X_test)

METHOD 2 - PCA

In [18]:
# Initialize PCA model
# pca = PCA(n_components=3)
# X_pca = pca.fit_transform(X_train_scaled)
# X_pca_df = pd.DataFrame(data=X_pca,columns=["principal component 1", "principal component 2", "principal component 3"])
# X_pca_df.head()

In [19]:
#Fetch the explained variance
# pca.explained_variance_ratio_

METHOD 3 - Lasso Regularization 

In [20]:
# Selecting features using Lasso regularization using SelectFromModel
sel_ = SelectFromModel(LogisticRegression(C=1,fit_intercept=False,penalty='l2'))
sel_.fit(scaler.transform(X_resampled), y_resampled)

SelectFromModel(estimator=LogisticRegression(C=1, fit_intercept=False))

In [21]:
# Visualising features that were kept by the lasso regularisation
sel_.get_support()

array([ True, False,  True, ..., False, False, False])

In [22]:
# Make a list of with the selected features
selected_feat = X_resampled.columns[(sel_.get_support())]
print('total features: {}'.format((X_resampled.shape[1])))
print('selected features: {}'.format(len(selected_feat)))
print('features with coefficients shrank to zero: {}'.format(
      np.sum(sel_.estimator_.coef_ == 0)))

total features: 1513
selected features: 579
features with coefficients shrank to zero: 0


In [23]:
# Number of features which coefficient was shrank to zero 
np.sum(sel_.estimator_.coef_ == 0)

0

In [24]:
# Identifying the removed features
removed_feats = X_resampled.columns[(sel_.estimator_.coef_ == 0).ravel().tolist()]
removed_feats

Index([], dtype='object')

In [25]:
# create new X test and train with 579 features
X_train_selected = sel_.transform(X_resampled.fillna(0))
X_test_selected = sel_.transform(X_test.fillna(0))
X_train_selected.shape, X_test_selected.shape

((48450, 579), (9774, 579))

In [63]:
# Export selected columns as csv for dashboard
X_selected_df = pd.DataFrame(selected_feat)
X_selected_df.to_csv('../Exports/X_selected_columns.csv')

# Model 1 -  ComplementNB Naive Bayes (with Lasso)

In [27]:
#Create classifier  
compNB_model = ComplementNB()

In [28]:
# Train the classifier 
compNB_model.fit(X_train_selected, y_resampled)

ComplementNB()

In [29]:
# Get predictions
y_pred = compNB_model.predict(X_test_selected)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            0       0
1            1       0
2            0       1
3            1       1
4            0       0
5            0       0
6            1       0
7            0       1
8            0       0
9            1       0
10           1       0
11           1       0
12           0       1
13           0       1
14           1       0
15           0       0
16           0       0
17           0       0
18           1       0
19           0       0

Evaluate the Model

In [30]:
# Get model's accuracy
print(accuracy_score(y_test, y_pred))

0.7219152854511971


In [31]:
# Confusion Matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[6026 2050]
 [ 668 1030]]


In [32]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.75      0.82      8076
           1       0.33      0.61      0.43      1698

    accuracy                           0.72      9774
   macro avg       0.62      0.68      0.62      9774
weighted avg       0.80      0.72      0.75      9774



# Model 2 -  GaussianNB Naive Bayes (with Lasso)

In [33]:
# Create classifier
GNB_model = GaussianNB()

In [34]:
# Train the classifier 
GNB_model.fit(X_train_selected, y_resampled)

GaussianNB()

In [35]:
# Get predictions
y_pred = GNB_model.predict(X_test_selected)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            0       0
1            1       0
2            1       1
3            1       1
4            0       0
5            1       0
6            1       0
7            1       1
8            1       0
9            1       0
10           1       0
11           1       0
12           0       1
13           1       1
14           0       0
15           0       0
16           1       0
17           0       0
18           1       0
19           0       0

Evaluate the Model

In [36]:
# Get model's accuracy
print(accuracy_score(y_test, y_pred))

0.4826069163085738


In [37]:
# Confusion Matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[3468 4608]
 [ 449 1249]]


In [38]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.43      0.58      8076
           1       0.21      0.74      0.33      1698

    accuracy                           0.48      9774
   macro avg       0.55      0.58      0.45      9774
weighted avg       0.77      0.48      0.54      9774



# Model 3 - Deep Neural Net model (with Lasso)

In [39]:
# Define the model - deep neural net
number_input_features = len(X_train_selected[0])
hidden_nodes_layer1 = 10
# hidden_nodes_layer2 = 5


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,input_dim= number_input_features, activation="relu"))

# # Second hidden layer 
# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Restore the model weights
#nn.load_weights("checkpoints/weights.100.hdf5")

# Check the structure of the model 
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                5800      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 5,811
Trainable params: 5,811
Non-trainable params: 0
_________________________________________________________________


In [40]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Change y_train and y_test type for tf
y_resampled_np = np.array(y_resampled)
y_test_np = np.array(y_test)

In [42]:
# Train the model
fit_model = nn.fit(X_train_selected,y_resampled_np,epochs=20)

Train on 48450 samples
Epoch 1/20
48450/48450 [==============================] - 3s 63us/sample - loss: 0.5165 - accuracy: 0.7717
Epoch 2/20
48450/48450 [==============================] - 2s 47us/sample - loss: 0.4405 - accuracy: 0.8071
Epoch 3/20
48450/48450 [==============================] - 2s 47us/sample - loss: 0.4125 - accuracy: 0.8185
Epoch 4/20
48450/48450 [==============================] - 2s 47us/sample - loss: 0.3929 - accuracy: 0.8276
Epoch 5/20
48450/48450 [==============================] - 2s 47us/sample - loss: 0.3786 - accuracy: 0.8353
Epoch 6/20
48450/48450 [==============================] - 2s 47us/sample - loss: 0.3669 - accuracy: 0.8412
Epoch 7/20
48450/48450 [==============================] - 2s 48us/sample - loss: 0.3574 - accuracy: 0.8451
Epoch 8/20
48450/48450 [==============================] - 2s 48us/sample - loss: 0.3487 - accuracy: 0.8493
Epoch 9/20
48450/48450 [==============================] - 2s 48us/sample - loss: 0.3425 - accuracy: 0.8523
Epoch 10/20
48

Evaluate the Model

In [43]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_selected,y_test_np,verbose=2)
print(f"Test Loss: {model_loss}, Test Accuracy: {model_accuracy}")

9774/1 - 0s - loss: 0.8930 - accuracy: 0.7222
Test Loss: 0.7771279870158743, Test Accuracy: 0.7222222089767456


In [44]:
model_loss, model_accuracy = nn.evaluate(X_train_selected,y_resampled_np,verbose=2)
print(f"Train Loss: {model_loss}, Train Accuracy: {model_accuracy}")

48450/1 - 1s - loss: 0.2025 - accuracy: 0.8790
Train Loss: 0.2870487046949142, Train Accuracy: 0.8790299296379089


In [45]:
# Confusion Matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[3468 4608]
 [ 449 1249]]


In [46]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.43      0.58      8076
           1       0.21      0.74      0.33      1698

    accuracy                           0.48      9774
   macro avg       0.55      0.58      0.45      9774
weighted avg       0.77      0.48      0.54      9774



# Model 4 - Random Forest Classifier (With Lasso)

In [47]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=50,random_state=78)

In [48]:
# Fitting the model
rf_model.fit(X_train_selected, y_resampled)

RandomForestClassifier(n_estimators=50, random_state=78)

In [49]:
# Get predictions
y_pred = rf_model.predict(X_test_selected)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction  Actual
0            0       0
1            0       0
2            0       1
3            1       1
4            0       0
5            0       0
6            0       0
7            0       1
8            0       0
9            1       0
10           1       0
11           0       0
12           1       1
13           0       1
14           1       0
15           0       0
16           0       0
17           0       0
18           1       0
19           0       0

Evaluate the Model

In [50]:
# Get model's accuracy
print(accuracy_score(y_test, y_pred))

0.7470841006752609


In [51]:
# Calculate feature importance in the Random Forest model
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.034608761984388135, 'deeper'),
 (0.01582036041856736, 'although'),
 (0.013754050568681491, 'cup'),
 (0.011829960439788241, 'guilti'),
 (0.010281904997499288, 'date'),
 (0.009335723408482472, 'front'),
 (0.0090286541962883, 'bei'),
 (0.008844881456684172, 'chase'),
 (0.008657676649329444, 'boat'),
 (0.008642497523805118, 'found'),
 (0.008369025837604906, 'child'),
 (0.008307115430169189, 'deni'),
 (0.008223746692191758, 'dream'),
 (0.008033854097248628, 'cheat'),
 (0.007787013622116781, 'dark'),
 (0.007730630410262488, 'groov'),
 (0.0076942529039233255, 'dare'),
 (0.007548324784522263, 'alway'),
 (0.007144807125568631, 'foot'),
 (0.0070371444553054665, 'chest'),
 (0.006971223904395576, 'cross'),
 (0.006889009119712068, 'bis'),
 (0.006794889003763532, 'clock'),
 (0.006614984485771749, 'beneath'),
 (0.006566924713457256, 'bang'),
 (0.006519054140712454, 'bist'),
 (0.00626042218751642, 'divin'),
 (0.006256919124761312, 'dog'),
 (0.006199866655046408, 'death'),
 (0.0061945519558473236, 

In [52]:
# Confusion Matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[6689 1387]
 [1085  613]]


In [53]:
# Classification Report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.83      0.84      8076
           1       0.31      0.36      0.33      1698

    accuracy                           0.75      9774
   macro avg       0.58      0.59      0.59      9774
weighted avg       0.76      0.75      0.76      9774



# Save the models

In [64]:
# Save the NB model as a pickle in a file 
joblib.dump(compNB_model, 'NB_model_v3.pkl') 

['NB_model_v3.pkl']

In [65]:
# Save the nn model as an h5 file
nn.save("nn_model_v3.h5")

In [66]:
# Save the NB model as a pickle in a file 
joblib.dump(rf_model, 'rf_model_joblib_v2.pkl') 

['rf_model_joblib_v2.pkl']

In [67]:
# Save the NB model as a pickle in a file 
pickle.dump(rf_model, open('rf_model_pickle_v2.pkl', 'wb'))